### ISSUE TITLE
npm run dev  error not work

### ISSUE THREAD

**Issue by djoudi** [vuravel/components#2]
with Laravel 6

![image](https://user-images.githubusercontent.com/152725/75613725-4f4a0e80-5b31-11ea-9114-49a47288a821.png)

**Comment by djoudi** [comment]
@vuravel

**Comment by djoudi** [comment]
the same error with laravel 5.8 

![image](https://user-images.githubusercontent.com/152725/75613983-f6c84080-5b33-11ea-836b-0c89dba25672.png)

**Comment by vuravel** [comment]
This is not related to vuravel packages. This is due to a bad installation of cross-env npm module.
See this for info on how to solve this issue: 
https://stackoverflow.com/questions/45034581/laravel-5-4-cross-env-is-not-recognized-as-an-internal-or-external-command
