### ISSUE TITLE
  It's not clear which file to import. Found:

### ISSUE THREAD

**Issue by djoudi** [vuravel/components#3]
ERROR in ./resources/sass/app.scss
Module build failed (from ./node_modules/css-loader/dist/cjs.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):

@import  'vuravel-catalog/sass/catalog';
        ^
      It's not clear which file to import. Found:
  node_modules\vuravel-catalog\sass\_catalog.scss
  node_modules\vuravel-catalog\sass\catalog.scss
   ╷
18 │ @import  'vuravel-catalog/sass/catalog';
   │          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by vuravel** [comment]
Did you install vuravel-components with the following command line?

`npm install --save vuravel-components`

This package will install the other ones: vuravel-form, vuravel-catalog and vuravel-menu

Check your node_modules folder and make sure you have **vuravel-catalog/sass/catalog.scss** inside

**Comment by djoudi** [comment]
Yes I install it
The problem with case-sensitive with Windows and linux

**Comment by djoudi** [comment]
There is to files catalog (Catalog and catalog) this is the problem with Windows system
But with Linux no problem
Please rename one of this file

**Comment by vuravel** [comment]
I see... I renamed one of the files. 

We should continue importing the file catalog as per the documentation:
`@import 'vuravel-catalog/sass/catalog';`

Let me know if it works now on Windows.

Thanks a lot for your input.
